image: 
  name: 148956472318.dkr.ecr.us-east-1.amazonaws.com/softwareplumbers/libgit2-dev-centos:latest
  entrypoint: ["/bin/bash", "-l", "-c"]

stages:
 - build
 - test

build:
  stage: build
  artifacts:
    paths:
     - build/libgit2.so
     - build/libgit2.so.26
     - build/libgit2.so.0.26.0
     - build/libgit2_clar
  script:
   - echo 'hello'
   - mkdir build
   - cd build
   - cmake ..
   - make

test:
  stage: test
  script:
   - cd build
   - libgit2_clar 
